language: ruby
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  - $COVPYYAML=cov3-default,coveralls3
  - $COVPYYAML=cov4-pyyaml,coveralls4
  - $COVPYYAML=cov41-pyyaml,coveralls41
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
  - pip install --user tox
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$COVPYYAML
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success: 
  - coveralls
