language: ruby
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CODECOV_TOKEN="eed1b96d-f794-4dbf-be89-f4572ced4993"
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
  - pip install --user codecov
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success: 
  - codecov
