language: ruby
dist: trusty
sudo: required

compiler:
  - gcc
addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - COVERALLS_TOKEN=gVXWoSj0aCbJngRymVCKxJ0SfLOIVYKzl
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
before_install:
  - pip install --user cpp-coveralls
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  - ./configure --enable-gcov && make && make check
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success: 
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
