language: ruby
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
  - pip install --user -r requirements.txt
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
#  - py.test --cov-report term-missing --cov=maths
#  - py.test --doctest-modules --cov=maths3 --cov-report term-missing
  - py.test
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success: 
  - coveralls
