language: ruby
dist: trusty
sudo: required
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  - $GOPATH/bin/goveralls -service=travis-ci
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success: 
  - coveralls
