language: ruby
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CODECOV_TOKEN="eed1b96d-f794-4dbf-be89-f4572ced4993"
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
  - pip install -e . --use-mirrors
 before_script:
  - pip install -r test_requirements.txt --use-mirrors
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
  - py.test example/tests.py --cov=example
  - cd -
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success: 
  - coveralls
