language: ruby
dist: trusty
sudo: required
go:
  - 1.2
  - tip
addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - COVERALLS_TOKEN=gVXWoSj0aCbJngRymVCKxJ0SfLOIVYKzl
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success: 
  - coveralls
