language: ruby
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - COVERALLS_REPO_TOKEN=gVXWoSj0aCbJngRymVCKxJ0SfLOIVYKzl
rvm:
  - 2.4.1
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
  #- pip install --user -r requirements.txt
after_script: 
  - NODE_ENV=_site istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  #- coverage report -m
cache:
  directories:
    - '$HOME/.sonar/cache'
#after_success:
  #- coveralls

