language: ruby
dist: trusty
sudo: required

node_js:
  - "node"
  - "8"
  - "6"
  - "5"
  - "4"
addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - COVERALLS_REPO_TOKEN=gVXWoSj0aCbJngRymVCKxJ0SfLOIVYKzl
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
  #- pip install --user -r requirements.txt
  - npm install -g mocha
  - npm install mocha --save-dev
  - npm install istanbul --save-dev
  - npm install --save-dev coveralls mocha-lcov-reporter
  #- npm install coveralls --save-dev
  #- npm install mocha-lcov-reporter --save-dev
  #- npm install --save-dev jest
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  #- coverage report -m
  #- make test-cov
  #- make test-coveralls
#before_script: npm install -g istanbul && npm install -g mocha
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success:
  #- coveralls
  #- make coveralls
  - npm run coveralls
