language: ruby
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hacklabsucre"
    token:
      secure: "ea3465f161020ebef5d1fa6fbb5b3397885683ce"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2.5
jdk:
  - oraclejdk8
install:
  - gem install jekyll
  - gem install html-proofer
 # - pip install --user -U pip
  - pip install --user python-coveralls
  - pip install --user coverage       # Add me to install coverage.py
  - pip install --user nose  
script:
  - jekyll build
  - htmlproofer _site --only-4xx
  - sonar-scanner
  - python setup.py install
  - nosetests --with-coverage # Add me to run nose with coverage support.
cache:
  directories:
    - '$HOME/.sonar/cache'
after_success:
  - coveralls
